// app/javascript/components/FlashMessages.tsx
import { usePage } from '@inertiajs/react'
import type { SharedProps } from '@/types'

export default function FlashMessages() {
  const { flash } = usePage<SharedProps>().props

  return (
    <>
      {flash.notice && <p>Notice: {flash.notice}</p>}
      {flash.alert && <p>Alert: {flash.alert}</p>}
    </>
  )
}

// app/javascript/components/FlashMessages.svelte
<script lang="ts">
  import { page } from '@inertiajs/svelte'
  import type { SharedProps } from '@/types'

  let shared = $derived($page.props as unknown as SharedProps)
</script>

{#if shared.flash.notice}
  <p>Notice: {shared.flash.notice}</p>
{/if}
{#if shared.flash.alert}
  <p>Alert: {shared.flash.alert}</p>
{/if}
