// app/javascript/components/Nav.svelte
<script lang="ts">
  import { page, router, Link } from '@inertiajs/svelte'
  import type { SharedProps } from '@/types'

  let shared = $derived($page.props as unknown as SharedProps)

  function signOut(e: Event) {
    e.preventDefault()
    router.delete(shared.sign_out_path)
  }
</script>

<nav>
  {#if shared.auth.user}
    <button onclick={signOut}>Sign Out</button>
  {:else}
    <Link href={shared.sign_in_path}>Sign In with Slack</Link>
  {/if}
</nav>

// app/javascript/components/Nav.tsx
import { usePage, router } from '@inertiajs/react'
import type { SharedProps } from '@/types'

export default function Nav() {
  const shared = usePage<SharedProps>().props

  function signOut(e: React.MouseEvent) {
    e.preventDefault()
    router.delete(shared.sign_out_path)
  }

  return (
    <nav>
      {shared.auth.user ? (
        <button onClick={signOut}>Sign Out</button>
      ) : (
        <a href={shared.sign_in_path}>Sign In with Slack</a>
      )}
    </nav>
  )
}
