// app/javascript/pages/Projects/Show.tsx
import { router, Link } from '@inertiajs/react'
import type { ProjectDetail } from '@/types'

function isSafeUrl(url: string | null): boolean {
  if (!url) return false
  try {
    const parsed = new URL(url)
    return parsed.protocol === 'http:' || parsed.protocol === 'https:'
  } catch {
    return false
  }
}

export default function ProjectsShow({
  project,
  can,
}: {
  project: ProjectDetail
  can: { update: boolean; destroy: boolean }
}) {
  function deleteProject() {
    if (confirm('Are you sure?')) {
      router.delete(`/projects/${project.id}`)
    }
  }

  return (
    <div className="max-w-4xl mx-auto py-8">
      <div className="flex items-center justify-between mb-6">
        <h1 className="font-bold text-4xl">{project.name}</h1>
        <div className="flex gap-2">
          {can.update && (
            <Link href={`/projects/${project.id}/edit`} className="bg-gray-200 px-4 py-2 rounded hover:bg-gray-300">
              Edit
            </Link>
          )}
          {can.destroy && (
            <button onClick={deleteProject} className="bg-red-600 text-white px-4 py-2 rounded hover:bg-red-700">
              Delete
            </button>
          )}
        </div>
      </div>

      {project.is_unlisted && (
        <span className="inline-block bg-yellow-100 text-yellow-800 text-sm px-2 py-1 rounded mb-4">Unlisted</span>
      )}

      {project.description && <p className="text-gray-700 mb-4">{project.description}</p>}

      {project.tags.length > 0 && (
        <div className="flex flex-wrap gap-2 mb-4">
          {project.tags.map((tag) => (
            <span key={tag} className="bg-gray-100 text-gray-700 text-sm px-2 py-1 rounded">
              {tag}
            </span>
          ))}
        </div>
      )}

      <div className="flex gap-4 text-sm text-gray-500 mb-6">
        {isSafeUrl(project.demo_link) && (
          <a href={project.demo_link!} target="_blank" rel="noopener" className="text-blue-600 hover:underline">
            Demo
          </a>
        )}
        {isSafeUrl(project.repo_link) && (
          <a href={project.repo_link!} target="_blank" rel="noopener" className="text-blue-600 hover:underline">
            Repository
          </a>
        )}
      </div>

      <p className="text-sm text-gray-500">
        Created by {project.user_display_name} on {project.created_at}
      </p>
    </div>
  )
}

// app/javascript/pages/Admin/Ships/Show.svelte
<script lang="ts">
  import { Link } from '@inertiajs/svelte'
  import type { AdminShipDetail } from '@/types'

  let { ship, can }: { ship: AdminShipDetail; can: { update: boolean } } = $props()

  function isSafeUrl(url: string | null): boolean {
    if (!url) return false
    try {
      const parsed = new URL(url)
      return parsed.protocol === 'http:' || parsed.protocol === 'https:'
    } catch {
      return false
    }
  }
</script>

<div class="max-w-4xl mx-auto py-8">
  <h1 class="font-bold text-4xl mb-2">Ship #{ship.id}</h1>
  <p class="text-gray-500 mb-6">for {ship.project_name} by {ship.user_display_name}</p>

  <div class="grid grid-cols-2 gap-4 mb-6">
    <div>
      <span class="text-sm text-gray-500">Status</span>
      <p class="capitalize">{ship.status}</p>
    </div>
    <div>
      <span class="text-sm text-gray-500">Reviewer</span>
      <p>{ship.reviewer_display_name ?? 'Unassigned'}</p>
    </div>
    <div>
      <span class="text-sm text-gray-500">Approved Seconds</span>
      <p>{ship.approved_seconds ?? '—'}</p>
    </div>
    <div>
      <span class="text-sm text-gray-500">Created</span>
      <p>{ship.created_at}</p>
    </div>
  </div>

  {#if ship.justification}
    <div class="mb-4">
      <span class="text-sm text-gray-500">Justification</span>
      <p class="mt-1">{ship.justification}</p>
    </div>
  {/if}

  {#if ship.feedback}
    <div class="mb-4">
      <span class="text-sm text-gray-500">Feedback</span>
      <p class="mt-1">{ship.feedback}</p>
    </div>
  {/if}

  <div class="grid grid-cols-2 gap-4 mb-6">
    <div>
      <span class="text-sm text-gray-500">Frozen Demo Link</span>
      <p>
        {#if isSafeUrl(ship.frozen_demo_link)}
          <a href={ship.frozen_demo_link} target="_blank" rel="noopener" class="text-blue-600 hover:underline">{ship.frozen_demo_link}</a>
        {:else}
          —
        {/if}
      </p>
    </div>
    <div>
      <span class="text-sm text-gray-500">Frozen Repo Link</span>
      <p>
        {#if isSafeUrl(ship.frozen_repo_link)}
          <a href={ship.frozen_repo_link} target="_blank" rel="noopener" class="text-blue-600 hover:underline">{ship.frozen_repo_link}</a>
        {:else}
          —
        {/if}
      </p>
    </div>
  </div>

  {#if can.update}
    <div class="mt-6">
      <Link href="/admin/reviews/{ship.id}/edit" class="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700">Edit</Link>
    </div>
  {/if}
</div>
