// app/javascript/pages/Admin/Projects/Index.svelte
<script lang="ts">
  import { router, Link } from '@inertiajs/svelte'
  import Pagination from '@/components/Pagination.svelte'
  import type { AdminProjectRow, PagyProps } from '@/types'

  let props: { projects: AdminProjectRow[]; pagy: PagyProps; query: string } = $props()
  let searchQuery = $state(props.query)

  function search(e: Event) {
    e.preventDefault()
    router.get('/admin/projects', { query: searchQuery }, { preserveState: true })
  }
</script>

<div class="max-w-6xl mx-auto py-8">
  <h1 class="font-bold text-4xl mb-6">Admin: Projects</h1>

  <form onsubmit={search} class="mb-6">
    <div class="flex gap-2">
      <input
        type="search"
        bind:value={searchQuery}
        placeholder="Search projects..."
        class="border rounded px-3 py-2 flex-1"
      />
      <button type="submit" class="bg-gray-200 px-4 py-2 rounded hover:bg-gray-300 cursor-pointer">Search</button>
    </div>
  </form>

  <table class="w-full border-collapse">
    <thead>
      <tr class="border-b text-left">
        <th class="py-2 px-3">Name</th>
        <th class="py-2 px-3">Owner</th>
        <th class="py-2 px-3">Ships</th>
        <th class="py-2 px-3">Unlisted</th>
        <th class="py-2 px-3">Created</th>
      </tr>
    </thead>
    <tbody>
      {#each props.projects as project}
        <tr class="border-b hover:bg-gray-50" class:opacity-50={project.is_discarded}>
          <td class="py-2 px-3">
            <Link href="/admin/projects/{project.id}" class="text-blue-600 hover:underline">{project.name}</Link>
            {#if project.is_discarded}
              <span class="text-xs text-red-500 ml-1">Deleted</span>
            {/if}
          </td>
          <td class="py-2 px-3"
            ><Link href="/admin/users/{project.user_id}" class="text-blue-600 hover:underline"
              >{project.user_display_name}</Link
            ></td
          >
          <td class="py-2 px-3">{project.ships_count}</td>
          <td class="py-2 px-3">{project.is_unlisted ? 'Yes' : 'No'}</td>
          <td class="py-2 px-3">{project.created_at}</td>
        </tr>
      {/each}
    </tbody>
  </table>

  <Pagination pagy={props.pagy} />
</div>

// app/javascript/pages/Projects/Index.tsx
import { useState } from 'react'
import { router, Link } from '@inertiajs/react'
import Pagination from '@/components/Pagination'
import type { ProjectCard, PagyProps } from '@/types'

export default function ProjectsIndex({
  projects,
  pagy,
  query,
}: {
  projects: ProjectCard[]
  pagy: PagyProps
  query: string
}) {
  const [searchQuery, setSearchQuery] = useState(query)

  function search(e: React.FormEvent) {
    e.preventDefault()
    router.get('/projects', { query: searchQuery }, { preserveState: true })
  }

  return (
    <div className="max-w-4xl mx-auto py-8">
      <div className="flex items-center justify-between mb-6">
        <h1 className="font-bold text-4xl">Projects</h1>
        <Link href="/projects/new" className="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700">
          New Project
        </Link>
      </div>

      <form onSubmit={search} className="mb-6">
        <div className="flex gap-2">
          <input
            type="search"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search projects..."
            className="border rounded px-3 py-2 flex-1"
          />
          <button type="submit" className="bg-gray-200 px-4 py-2 rounded hover:bg-gray-300 cursor-pointer">
            Search
          </button>
        </div>
      </form>

      {projects.length > 0 ? (
        <>
          {projects.map((project) => (
            <div key={project.id} className="border rounded-lg p-4 mb-4">
              <div className="flex items-center justify-between">
                <h2 className="text-xl font-semibold">
                  <Link href={`/projects/${project.id}`} className="hover:underline">
                    {project.name}
                  </Link>
                </h2>
                {project.is_unlisted && <span className="text-sm text-gray-500">Unlisted</span>}
              </div>

              {project.description && <p className="text-gray-600 mt-2">{project.description}</p>}

              {project.tags.length > 0 && (
                <div className="flex flex-wrap gap-2 mt-2">
                  {project.tags.map((tag) => (
                    <span key={tag} className="bg-gray-100 text-gray-700 text-sm px-2 py-1 rounded">
                      {tag}
                    </span>
                  ))}
                </div>
              )}

              <div className="flex gap-4 mt-3 text-sm text-gray-500">
                <span>by {project.user_display_name}</span>
                <span>{project.ships_count} ships</span>
              </div>
            </div>
          ))}

          <Pagination pagy={pagy} />
        </>
      ) : (
        <p className="text-gray-500">No projects yet.</p>
      )}
    </div>
  )
}
