// app/javascript/pages/Admin/Projects/Show.svelte
<script lang="ts">
  import { Link } from '@inertiajs/svelte'
  import type { AdminProjectDetail } from '@/types'

  let { project, ships }: {
    project: AdminProjectDetail
    ships: { id: number; status: string; reviewer_display_name: string | null; approved_seconds: number | null; created_at: string }[]
  } = $props()

  function isSafeUrl(url: string | null): boolean {
    if (!url) return false
    try {
      const parsed = new URL(url)
      return parsed.protocol === 'http:' || parsed.protocol === 'https:'
    } catch {
      return false
    }
  }
</script>

<div class="max-w-4xl mx-auto py-8">
  <h1 class="font-bold text-4xl mb-2">
    {project.name}
    {#if project.is_discarded}
      <span class="text-sm text-red-500 font-normal">Deleted on {project.discarded_at}</span>
    {/if}
  </h1>
  <p class="text-gray-500 mb-6">Owned by <Link href="/admin/users/{project.user_id}" class="text-blue-600 hover:underline">{project.user_display_name}</Link></p>

  <div class="grid grid-cols-2 gap-4 mb-6">
    <div>
      <span class="text-sm text-gray-500">Unlisted</span>
      <p>{project.is_unlisted ? 'Yes' : 'No'}</p>
    </div>
    <div>
      <span class="text-sm text-gray-500">Tags</span>
      <p>{project.tags.length > 0 ? project.tags.join(', ') : 'None'}</p>
    </div>
    <div>
      <span class="text-sm text-gray-500">Demo Link</span>
      <p>
        {#if isSafeUrl(project.demo_link)}
          <a href={project.demo_link} target="_blank" rel="noopener" class="text-blue-600 hover:underline">{project.demo_link}</a>
        {:else}
          None
        {/if}
      </p>
    </div>
    <div>
      <span class="text-sm text-gray-500">Repo Link</span>
      <p>
        {#if isSafeUrl(project.repo_link)}
          <a href={project.repo_link} target="_blank" rel="noopener" class="text-blue-600 hover:underline">{project.repo_link}</a>
        {:else}
          None
        {/if}
      </p>
    </div>
  </div>

  {#if project.description}
    <div class="mb-6">
      <span class="text-sm text-gray-500">Description</span>
      <p class="mt-1">{project.description}</p>
    </div>
  {/if}

  <h2 class="font-bold text-2xl mb-4">Ships ({ships.length})</h2>

  {#if ships.length > 0}
    <table class="w-full border-collapse">
      <thead>
        <tr class="border-b text-left">
          <th class="py-2 px-3">Status</th>
          <th class="py-2 px-3">Reviewer</th>
          <th class="py-2 px-3">Approved Seconds</th>
          <th class="py-2 px-3">Created</th>
          <th class="py-2 px-3"></th>
        </tr>
      </thead>
      <tbody>
        {#each ships as ship}
          <tr class="border-b hover:bg-gray-50">
            <td class="py-2 px-3"><span class="capitalize">{ship.status}</span></td>
            <td class="py-2 px-3">{ship.reviewer_display_name ?? 'Unassigned'}</td>
            <td class="py-2 px-3">{ship.approved_seconds ?? '—'}</td>
            <td class="py-2 px-3">{ship.created_at}</td>
            <td class="py-2 px-3"><Link href="/admin/reviews/{ship.id}" class="text-blue-600 hover:underline">View</Link></td>
          </tr>
        {/each}
      </tbody>
    </table>
  {:else}
    <p class="text-gray-500">No ships yet.</p>
  {/if}
</div>

// app/javascript/pages/Projects/Show.tsx
import { router, Link } from '@inertiajs/react'
import type { ProjectDetail } from '@/types'

function isSafeUrl(url: string | null): boolean {
  if (!url) return false
  try {
    const parsed = new URL(url)
    return parsed.protocol === 'http:' || parsed.protocol === 'https:'
  } catch {
    return false
  }
}

export default function ProjectsShow({
  project,
  can,
}: {
  project: ProjectDetail
  can: { update: boolean; destroy: boolean }
}) {
  function deleteProject() {
    if (confirm('Are you sure?')) {
      router.delete(`/projects/${project.id}`)
    }
  }

  return (
    <div className="max-w-4xl mx-auto py-8">
      <div className="flex items-center justify-between mb-6">
        <h1 className="font-bold text-4xl">{project.name}</h1>
        <div className="flex gap-2">
          {can.update && (
            <Link href={`/projects/${project.id}/edit`} className="bg-gray-200 px-4 py-2 rounded hover:bg-gray-300">
              Edit
            </Link>
          )}
          {can.destroy && (
            <button onClick={deleteProject} className="bg-red-600 text-white px-4 py-2 rounded hover:bg-red-700">
              Delete
            </button>
          )}
        </div>
      </div>

      {project.is_unlisted && (
        <span className="inline-block bg-yellow-100 text-yellow-800 text-sm px-2 py-1 rounded mb-4">Unlisted</span>
      )}

      {project.description && <p className="text-gray-700 mb-4">{project.description}</p>}

      {project.tags.length > 0 && (
        <div className="flex flex-wrap gap-2 mb-4">
          {project.tags.map((tag) => (
            <span key={tag} className="bg-gray-100 text-gray-700 text-sm px-2 py-1 rounded">
              {tag}
            </span>
          ))}
        </div>
      )}

      <div className="flex gap-4 text-sm text-gray-500 mb-6">
        {isSafeUrl(project.demo_link) && (
          <a href={project.demo_link!} target="_blank" rel="noopener" className="text-blue-600 hover:underline">
            Demo
          </a>
        )}
        {isSafeUrl(project.repo_link) && (
          <a href={project.repo_link!} target="_blank" rel="noopener" className="text-blue-600 hover:underline">
            Repository
          </a>
        )}
      </div>

      <p className="text-sm text-gray-500">
        Created by {project.user_display_name} on {project.created_at}
      </p>
    </div>
  )
}
